version: '3.5'

services:
 postgresdb:
  build: ./databaseConfig
  restart: unless-stopped
  environment:
   POSTGRES_USER: hubert
   POSTGRES_PASSWORD: superuser
   POSTGRES_DB: studentdatastorage
  container_name: postgresdb
  expose:
    - "5433"
  command: -p 5433
  ports:
    - "5433:5433"
  volumes:
   - database:/var/lib/postgresql/data
 
 student-data-storage:
  build: .
  container_name: student-data-storage-compose
  ports:
   - 8080:8080
   
volumes:
  database:
 

